-- Communes of the Metropolitan Region of Santiago.
insert into public.comunas (nombre)
values
    ('Alhué'),
    ('Buin'),
    ('Calera de Tango'),
    ('Cerrillos'),
    ('Cerro Navia'),
    ('Colina'),
    ('Conchalí'),
    ('Curacaví'),
    ('El Bosque'),
    ('El Monte'),
    ('Estación Central'),
    ('Huechuraba'),
    ('Independencia'),
    ('Isla de Maipo'),
    ('La Cisterna'),
    ('La Florida'),
    ('La Granja'),
    ('La Pintana'),
    ('La Reina'),
    ('Lampa'),
    ('Las Condes'),
    ('Lo Barnechea'),
    ('Lo Espejo'),
    ('Lo Prado'),
    ('Macul'),
    ('Maipú'),
    ('María Pinto'),
    ('Melipilla'),
    ('Ñuñoa'),
    ('Padre Hurtado'),
    ('Paine'),
    ('Pedro Aguirre Cerda'),
    ('Peñaflor'),
    ('Peñalolén'),
    ('Pirque'),
    ('Providencia'),
    ('Pudahuel'),
    ('Puente Alto'),
    ('Quilicura'),
    ('Quinta Normal'),
    ('Recoleta'),
    ('Renca'),
    ('San Bernardo'),
    ('San Joaquín'),
    ('San José de Maipo'),
    ('San Miguel'),
    ('San Pedro'),
    ('San Ramón'),
    ('Santiago'),
    ('Talagante'),
    ('Tiltil'),
    ('Vitacura')
on conflict (nombre) do update
set activa = true;

-- Los datos iniciales de categorías se agregarán junto con la migración de servicios.
